name: Changes Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Boot Simulator
      run: xcrun simctl boot 5E4C21FA-303F-461E-81AD-F50D186A79FC
    - name: Build Network Monitor
      run: xcodebuild build -scheme NetworkMonitor -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
    - name: Test Network Monitor
      run: xcodebuild clean test -scheme NetworkMonitor -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Pod lib lint
      run: pod lib lint FNMNetworkMonitor.podspec --allow-warnings --analyze
