name: Changes Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Network Monitor
      run: xcodebuild build -scheme NetworkMonitor -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'       
    - name: Test Network Monitor
      run: xcodebuild test -scheme NetworkMonitor -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'      
    - name: Build Sample
      run: xcodebuild build -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'       
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Pod lib lint
      run: pod lib lint FNMNetworkMonitor.podspec --allow-warnings --analyze

